name: Build LaTeX document and Generate README
on: [push]
jobs:
  build_latex_and_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: jeff-curriculum.tex
          latexmk_use_xelatex: true

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: List directory contents
        run: ls -la

      - name: Upload PDF to curriculum-vitae branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Intentar cambiar a la rama curriculum-vitae-pdf si existe
          if git show-ref --verify --quiet refs/remotes/origin/curriculum-vitae-pdf; then
            git checkout curriculum-vitae-pdf
          else
            # Si la rama no existe, crear una nueva rama vacía
            git checkout --orphan curriculum-vitae-pdf
            git rm -rf .
          fi
          
          # Verificar y copiar el PDF
          if [ -f "jeff-curriculum.pdf" ]; then
            cp jeff-curriculum.pdf ./jeff-curriculum-es.pdf
          else
            echo "jeff-curriculum.pdf not found, creating empty file"
            touch jeff-curriculum-es.pdf
          fi
          
          # Añadir y hacer commit del PDF con fecha
          git add jeff-curriculum-es.pdf
          git commit -m "feat: Actualiza curriculum - ${{ steps.date.outputs.date }}" || echo "No changes to commit"
          
          # Push al branch (sin --force para mantener historial)
          git push origin curriculum-vitae-pdf

      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: curriculum-vitae-pdf
          path: jeff-curriculum-es.pdf
